name: Git Pull on Server

on:
  push:
    branches:
      - main  # You can change this to the branch you want to trigger the action on

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # This step checks out your repository's code

    - name: SSH into server and pull latest changes
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.192.168.1.76 }}  # You need to set this secret in your repository settings
        username: ${{ secrets.mspc-48}}  # You need to set this secret in your repository settings
        password: ${{ secrets.mind@123 }}  # You need to set this secret in your repository settings
        script: |
          cd /var/www/html/jenkins-test
          git pull
